### ISSUE TITLE
collect2: Error

### ISSUE THREAD

**Issue by Deickar** [Futureblur/magnet#18]
Everything works fine, but when you run the "magnet build" command, everything breaks.

Error is : collect2: Error: LD returned output status 1.

The Error in More Detail:

FAILED: /home/username/progra/CPP/CPP/proyectos/prueba2_mg/prueb
: && /usr/lib64/ccache/c++ -g -Wl, prueba2_mg/Source/CMakeFiles/
/CPP/CPP/proyectos/prueba2_mg/prueba2_mg/Binaries/Debug/prueba2_
/usr/bin/ld: Can't find :  There is no file or d
collect2: error: LD returned output status 1
ninja: build stopped: subcommand failed.

operating system: fedora linux 39  (Workstation Edition)
Kernel: 6.6.7-200.fc39.x86_64
wm: Hyperland.

**Comment by rdsov** [comment]
Does your code compile? If yes, this appears to be a linker error. In this case you appear to be using a function that is not in the STL, hence why you would need to provide a linker flag. This issue is being described in detail [here](https://stackoverflow.com/questions/27272525/what-does-collect2-error-ld-returned-1-exit-status-mean).
Also, are you using a dependency?

**Comment by rdsov** [comment]
Thank you for your contribution! #20 solves this issue.
